-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE `logs` (
	`id` int(11) AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`category` varchar(50) NOT NULL,
	`subcategory` varchar(50) NOT NULL,
	`status` varchar(50) NOT NULL,
	`assignedTo` varchar(100) DEFAULT 'NULL',
	`location` varchar(100) DEFAULT 'NULL',
	`purchaseDate` date DEFAULT 'NULL',
	`value` float DEFAULT 'NULL',
	`serialNumber` varchar(100) NOT NULL,
	`createdAt` datetime NOT NULL,
	`updatedAt` datetime NOT NULL,
	CONSTRAINT `serialNumber` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_2` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_3` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_4` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_5` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_6` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_7` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_8` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_9` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_10` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_11` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_12` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_13` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_14` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_15` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_16` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_17` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_18` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_19` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_20` UNIQUE(`serialNumber`),
	CONSTRAINT `serialNumber_21` UNIQUE(`serialNumber`)
);
--> statement-breakpoint
CREATE TABLE `stacks` (
	`id` int(11) AUTO_INCREMENT NOT NULL,
	`title` varchar(50) NOT NULL,
	`description` varchar(50) NOT NULL,
	`createdAt` datetime NOT NULL,
	`updatedAt` datetime NOT NULL
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int(10) unsigned AUTO_INCREMENT NOT NULL,
	`firstName` varchar(255) NOT NULL,
	`lastName` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`password` varchar(255) NOT NULL,
	`isAdmin` tinyint(1) NOT NULL DEFAULT 0,
	`createdAt` datetime NOT NULL,
	`updatedAt` datetime NOT NULL,
	CONSTRAINT `email` UNIQUE(`email`),
	CONSTRAINT `email_2` UNIQUE(`email`),
	CONSTRAINT `email_3` UNIQUE(`email`),
	CONSTRAINT `email_4` UNIQUE(`email`),
	CONSTRAINT `email_5` UNIQUE(`email`),
	CONSTRAINT `email_6` UNIQUE(`email`),
	CONSTRAINT `email_7` UNIQUE(`email`),
	CONSTRAINT `email_8` UNIQUE(`email`),
	CONSTRAINT `email_9` UNIQUE(`email`),
	CONSTRAINT `email_10` UNIQUE(`email`),
	CONSTRAINT `email_11` UNIQUE(`email`),
	CONSTRAINT `email_12` UNIQUE(`email`),
	CONSTRAINT `email_13` UNIQUE(`email`),
	CONSTRAINT `email_14` UNIQUE(`email`),
	CONSTRAINT `email_15` UNIQUE(`email`),
	CONSTRAINT `email_16` UNIQUE(`email`),
	CONSTRAINT `email_17` UNIQUE(`email`),
	CONSTRAINT `email_18` UNIQUE(`email`),
	CONSTRAINT `email_19` UNIQUE(`email`),
	CONSTRAINT `email_20` UNIQUE(`email`),
	CONSTRAINT `email_21` UNIQUE(`email`),
	CONSTRAINT `email_22` UNIQUE(`email`),
	CONSTRAINT `email_23` UNIQUE(`email`),
	CONSTRAINT `email_24` UNIQUE(`email`),
	CONSTRAINT `email_25` UNIQUE(`email`),
	CONSTRAINT `email_26` UNIQUE(`email`),
	CONSTRAINT `email_27` UNIQUE(`email`),
	CONSTRAINT `email_28` UNIQUE(`email`),
	CONSTRAINT `email_29` UNIQUE(`email`),
	CONSTRAINT `email_30` UNIQUE(`email`),
	CONSTRAINT `email_31` UNIQUE(`email`),
	CONSTRAINT `email_32` UNIQUE(`email`),
	CONSTRAINT `email_33` UNIQUE(`email`),
	CONSTRAINT `email_34` UNIQUE(`email`),
	CONSTRAINT `email_35` UNIQUE(`email`),
	CONSTRAINT `email_36` UNIQUE(`email`),
	CONSTRAINT `email_37` UNIQUE(`email`),
	CONSTRAINT `email_38` UNIQUE(`email`),
	CONSTRAINT `email_39` UNIQUE(`email`),
	CONSTRAINT `email_40` UNIQUE(`email`),
	CONSTRAINT `email_41` UNIQUE(`email`),
	CONSTRAINT `email_42` UNIQUE(`email`),
	CONSTRAINT `email_43` UNIQUE(`email`),
	CONSTRAINT `email_44` UNIQUE(`email`),
	CONSTRAINT `email_45` UNIQUE(`email`),
	CONSTRAINT `email_46` UNIQUE(`email`),
	CONSTRAINT `email_47` UNIQUE(`email`),
	CONSTRAINT `email_48` UNIQUE(`email`),
	CONSTRAINT `email_49` UNIQUE(`email`),
	CONSTRAINT `email_50` UNIQUE(`email`),
	CONSTRAINT `email_51` UNIQUE(`email`),
	CONSTRAINT `email_52` UNIQUE(`email`),
	CONSTRAINT `email_53` UNIQUE(`email`),
	CONSTRAINT `email_54` UNIQUE(`email`),
	CONSTRAINT `email_55` UNIQUE(`email`)
);

*/